apiVersion: v1
kind: Service
metadata:
  name: dev-ondc-api-gcp-lb-service
  namespace: namaste
  labels:
    app.kubernetes.io/name: dev-ondc-api
spec:
  type: NodePort
  selector:
    role: ondc-api
    env: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
